### ISSUE TITLE
Invalid header field value Bearer

### ISSUE THREAD

**Issue by iohenkies** [cbeneke/hcloud-fip-controller#54]
Hi,

Some months ago I was able to setup everything with the fip-controller and now I'm trying again with a fresh install. But installing via the yml manifests as with a helm install results in the same error in the logs in fip controller deployment or deamonset:

`time="2020-08-30T10:55:12Z" level=fatal msg="Could not run controller: could not get configured server: could not fetch servers: Get \"https://api.hetzner.cloud/v1/servers?page=1&per_page=50\": net/http: invalid header field value \"Bearer ꌰ��$\\x06\\t��\\f4�\\u0096��ˇ���\\x19\\x05\\x19�\\f�����]O�������\\x10n$Vg�g\"  for key Authorization" func="github.com/sirupsen/logrus.(*Entry).Logf" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:314"`

Any idea?

**Comment by iohenkies** [comment]
Lol solved after many hours I can tell you :)

The secret should be like this:

```
apiVersion: v1
kind: Secret
metadata:
  name: fip-controller-secrets
stringData:
  HCLOUD_API_TOKEN: "snip"
```

Instead of this:

```
apiVersion: v1
kind: Secret
metadata:
  name: fip-controller-secrets
data:
  HCLOUD_API_TOKEN: "snip"
```
